### ISSUE TITLE
Crashes when using DividerItemDecoration

### ISSUE THREAD

**Issue by MahmoudB** [serso/android-linear-layout-manager#12]
My app crashes when using the following line of code:
```mRecyclerView.addItemDecoration(new DividerItemDecoration(this, null));```

Here is the stacktrace:
    ```java.lang.NoSuchMethodError: android.support.v7.widget.RecyclerView$LayoutParams.getViewLayoutPosition
            at org.solovyev.android.views.llm.DividerItemDecoration.getItemOffsets(DividerItemDecoration.java:63)
            at android.support.v7.widget.RecyclerView.getItemDecorInsetsForChild(RecyclerView.java:2662)
            at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:5434)
            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1328)
            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1265)
            at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:522)
            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:1918)
            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2155)
            at android.view.View.layout(View.java:15745)
            at android.view.ViewGroup.layout(ViewGroup.java:4867)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
            at android.view.View.layout(View.java:15745)
            at android.view.ViewGroup.layout(ViewGroup.java:4867)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:15745)
            at android.view.ViewGroup.layout(ViewGroup.java:4867)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
            at android.view.View.layout(View.java:15745)
            at android.view.ViewGroup.layout(ViewGroup.java:4867)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:15745)
            at android.view.ViewGroup.layout(ViewGroup.java:4867)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
            at android.view.View.layout(View.java:15745)
            at android.view.ViewGroup.layout(ViewGroup.java:4867)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:15745)
            at android.view.ViewGroup.layout(ViewGroup.java:4867)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2356)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2069)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6632)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:814)
            at android.view.Choreographer.doCallbacks(Choreographer.java:614)
            at android.view.Choreographer.doFrame(Choreographer.java:584)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:800)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5487)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)```

**Comment by serso** [comment]
Which version of support library do you use? Do you use proguard? Virtual machine for some reason can't find "getViewLayoutPosition" method which seems really strange and probably is caused by some misconfiguration in your project.

**Comment by MahmoudB** [comment]
I use the latest version of support 22.2.1, no proguard.

**Comment by serso** [comment]
No repro.
