### ISSUE TITLE
Crashes when using adapter.notifyItemRemoved(position)

### ISSUE THREAD

**Issue by WillSarah** [serso/android-linear-layout-manager#7]
Hi, 

when using this library for LinearLayoutManager, I get the following crash when calling adapter.notifyItemRemoved(position) directly after removing a data item from the data set. With the original LinearLayoutManager from the SupportLibrary everything works fine (but of course I don't get the wrap_content feature that I need)

Edit: I am setting the RecyclerView's parent layout height to a fixed size if it exceeds a certain height - this crash only seems to happen when I do in fact set a fixed height to the parent view (in code). If the parent view's height is set to wrap_content (default xml) as well, this crash does not occur. 

In this example, the item at index 3 is being removed:

```
06-24 11:02:07.141: E/AndroidRuntime(24063): FATAL EXCEPTION: main
06-24 11:02:07.141: E/AndroidRuntime(24063): Process: xxx, PID: 24063
06-24 11:02:07.141: E/AndroidRuntime(24063): java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 4(offset:-1).state:8
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4041)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3999)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at org.solovyev.android.views.llm.LinearLayoutManager.measureChild(LinearLayoutManager.java:220)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at org.solovyev.android.views.llm.LinearLayoutManager.onMeasure(LinearLayoutManager.java:113)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2081)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.view.View.measure(View.java:17430)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.view.View.measure(View.java:17430)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.view.View.measure(View.java:17430)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.view.View.measure(View.java:17430)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.view.View.measure(View.java:17430)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2560)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.view.View.measure(View.java:17430)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2001)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1166)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1372)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.view.Choreographer.doFrame(Choreographer.java:550)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.os.Handler.handleCallback(Handler.java:739)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.os.Looper.loop(Looper.java:135)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at java.lang.reflect.Method.invoke(Native Method)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at java.lang.reflect.Method.invoke(Method.java:372)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
06-24 11:02:07.141: E/AndroidRuntime(24063): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

```

**Comment by serso** [comment]
Can you please post a code example and xml layout?

**Comment by WillSarah** [comment]
I typed up a quick sample project that demonstrates the issue, I hope that helps: https://github.com/kupferwerk/llm-wrapped-list-sample

(Tapping an item in the dialog adds another item to list after it, after a delay of 3sec the item is removed again, then the crash should occur. Sometimes it doesn't, but I could not detect a pattern for that behaviour yet)

**Comment by MahmoudB** [comment]
@WillSarah I encountered the same issue, and I fixed it by adding a try catch IndexOutOfBoundsException around the content of measureChild method.

Hope it helps.
